import { Hono, type Context } from 'hono';
import { render } from '../render';
import { type AppEnv, requireRental } from '../middleware';
import { r2Service } from '../services/r2_service';
import { getUserVoximplantCredentials } from '../services/user_voximplant_service';
import { ensureVoximplantCallerId, VoximplantManagementService } from '../services/voximplant_management_service';
import { pyDate } from '../date';
import { hasUserTwilioCredentials } from '../services/user_twilio_service';

export const assetsRoutes = new Hono<AppEnv>();
assetsRoutes.use('*', requireRental);
const truthy=(v:unknown)=>['1','true','yes','on'].includes(String(v??'').toLowerCase());
const idOf=(c:Context<AppEnv>,name='id')=>Number(c.req.param(name));

async function caller(c:Context<AppEnv>,id:number){ return c.env.DB.prepare('SELECT * FROM caller_ids WHERE id=? AND user_id=?').bind(id,c.get('user').id).first<Record<string,any>>(); }
async function audio(c:Context<AppEnv>,id:number){ return c.env.DB.prepare('SELECT * FROM audios WHERE id=? AND user_id=?').bind(id,c.get('user').id).first<Record<string,any>>(); }
function callerView(row:Record<string,any>){return {...row,vox_verification_status:{value:row.vox_verification_status},vox_last_verification_at:row.vox_last_verification_at?pyDate(row.vox_last_verification_at):null};}

assetsRoutes.get('/caller-ids',async(c)=>{ const rows=await c.env.DB.prepare(`SELECT ci.*,cps.status twilio_status,cps.checked_at twilio_checked_at,cps.error twilio_error FROM caller_ids ci LEFT JOIN caller_id_provider_status cps ON cps.caller_id_id=ci.id AND cps.provider='twilio' WHERE ci.user_id=? ORDER BY ci.country_code,ci.phone_number`).bind(c.get('user').id).all<Record<string,any>>(); const creds=await getUserVoximplantCredentials(c.env,c.env.DB,c.get('user').id); return c.html(render('assets/caller_ids/list.html',{request:{url:c.req.url},user:c.get('user'),caller_ids:rows.results.map(callerView),twilio_configured:await hasUserTwilioCredentials(c.env,c.env.DB,c.get('user').id),voximplant_configured:Boolean(creds),created:truthy(c.req.query('created')),deleted:truthy(c.req.query('deleted')),verified:truthy(c.req.query('verified')),error:c.req.query('error')??null})); });
assetsRoutes.get('/caller-ids/create',(c)=>c.html(render('assets/caller_ids/create.html',{request:{url:c.req.url},user:c.get('user'),error:null})));
assetsRoutes.post('/caller-ids/create',async(c)=>{ const b=await c.req.parseBody(),phone=String(b.phone_number??'').trim(),country=String(b.country_code??'').trim().toUpperCase(); const ctx={request:{url:c.req.url},user:c.get('user')}; if(!/^\+[1-9]\d{1,14}$/.test(phone)) return c.html(render('assets/caller_ids/create.html',{...ctx,error:'Invalid phone number. Use E.164 format (e.g., +15551234567).'}),400); if(await c.env.DB.prepare('SELECT 1 FROM caller_ids WHERE phone_number=?').bind(phone).first()) return c.html(render('assets/caller_ids/create.html',{...ctx,error:'This phone number is already registered.'}),400); await c.env.DB.prepare("INSERT INTO caller_ids(user_id,phone_number,country_code,description,is_active,vox_verification_status) VALUES(?,?,?,?,1,'not_started')").bind(c.get('user').id,phone,country,String(b.description??'').trim()).run(); return c.redirect('/assets/caller-ids?created=true',302); });
assetsRoutes.get('/caller-ids/:id/edit',async(c)=>{ const row=await caller(c,idOf(c)); if(!row)return c.json({detail:'Caller ID not found'},404); return c.html(render('assets/caller_ids/edit.html',{request:{url:c.req.url},user:c.get('user'),caller_id:callerView(row),error:null})); });
assetsRoutes.post('/caller-ids/:id/edit',async(c)=>{ const id=idOf(c),row=await caller(c,id); if(!row)return c.json({detail:'Caller ID not found'},404); const b=await c.req.parseBody(),phone=String(b.phone_number??'').trim(),country=String(b.country_code??'').trim().toUpperCase(); if(!/^\+[1-9]\d{1,14}$/.test(phone)) return c.html(render('assets/caller_ids/edit.html',{request:{url:c.req.url},user:c.get('user'),caller_id:callerView(row),error:'Invalid phone number. Use E.164 format.'}),400); if(await c.env.DB.prepare('SELECT 1 FROM caller_ids WHERE phone_number=? AND id<>?').bind(phone,id).first()) return c.html(render('assets/caller_ids/edit.html',{request:{url:c.req.url},user:c.get('user'),caller_id:callerView(row),error:'This phone number is already registered.'}),400); const changed=row.phone_number!==phone; await c.env.DB.prepare('UPDATE caller_ids SET phone_number=?,country_code=?,description=?,is_active=?,vox_callerid_id=?,vox_verification_status=?,vox_last_verification_at=? WHERE id=?').bind(phone,country,String(b.description??'').trim(),truthy(b.is_active)?1:0,changed?null:row.vox_callerid_id,changed?'not_started':row.vox_verification_status,changed?null:row.vox_last_verification_at,id).run(); if(changed)await c.env.DB.prepare("DELETE FROM caller_id_provider_status WHERE caller_id_id=? AND provider='twilio'").bind(id).run(); return c.redirect('/assets/caller-ids',302); });
assetsRoutes.post('/caller-ids/:id/voximplant/verify',async(c)=>{ const id=idOf(c),row=await caller(c,id); if(!row)return c.json({detail:'Caller ID not found'},404); const creds=await getUserVoximplantCredentials(c.env,c.env.DB,c.get('user').id); if(!creds)return c.redirect('/assets/caller-ids?error='+encodeURIComponent('Configure Voximplant credentials in Settings before verifying numbers.'),302); try{ const result=await ensureVoximplantCallerId({vox_callerid_id:row.vox_callerid_id,phone_number:row.phone_number},creds); const voxId=Number(result.callerid_id??result.caller_id??row.vox_callerid_id)||null; if(!voxId) throw new Error('Voximplant returned no caller ID'); await VoximplantManagementService(creds).verifyCallerId(voxId); await c.env.DB.prepare("UPDATE caller_ids SET vox_callerid_id=?,vox_verification_status='pending',vox_last_verification_at=? WHERE id=?").bind(voxId,new Date().toISOString(),id).run(); return c.redirect('/assets/caller-ids',302); }catch(e){await c.env.DB.prepare("UPDATE caller_ids SET vox_verification_status='failed' WHERE id=?").bind(id).run(); return c.redirect('/assets/caller-ids?error='+encodeURIComponent(`Voximplant verification failed: ${e instanceof Error?e.message:e}`),302);} });
assetsRoutes.post('/caller-ids/:id/voximplant/activate',async(c)=>{ const id=idOf(c),row=await caller(c,id),creds=await getUserVoximplantCredentials(c.env,c.env.DB,c.get('user').id); if(!row)return c.json({detail:'Caller ID not found'},404); if(!creds||!row.vox_callerid_id)return c.redirect('/assets/caller-ids?error='+encodeURIComponent('Start Voximplant verification before activating this number.'),302); try{await VoximplantManagementService(creds).activateCallerId(row.vox_callerid_id,String((await c.req.parseBody()).verification_code??'').trim()); await c.env.DB.prepare("UPDATE caller_ids SET vox_verification_status='verified' WHERE id=?").bind(id).run(); return c.redirect('/assets/caller-ids?verified=true',302);}catch(e){await c.env.DB.prepare("UPDATE caller_ids SET vox_verification_status='failed' WHERE id=?").bind(id).run(); return c.redirect('/assets/caller-ids?error='+encodeURIComponent(`Activation failed: ${e instanceof Error?e.message:e}`),302);} });
assetsRoutes.post('/caller-ids/:id/delete',async(c)=>{ const id=idOf(c),row=await caller(c,id); if(!row)return c.json({detail:'Caller ID not found'},404); const used=await c.env.DB.prepare('SELECT COUNT(*) count FROM campaigns WHERE caller_id_id=?').bind(id).first<{count:number}>(); if(used?.count)return c.redirect('/assets/caller-ids?error='+encodeURIComponent('Cannot delete: this Caller ID is already used by campaigns'),302); await c.env.DB.prepare('DELETE FROM caller_ids WHERE id=?').bind(id).run(); return c.redirect('/assets/caller-ids?deleted=true',302); });

assetsRoutes.get('/audios',async(c)=>{const rows=await c.env.DB.prepare('SELECT * FROM audios WHERE user_id=? ORDER BY created_at DESC').bind(c.get('user').id).all();return c.html(render('assets/audios/list.html',{request:{url:c.req.url},user:c.get('user'),audios:rows.results,uploaded:truthy(c.req.query('uploaded')),deleted:truthy(c.req.query('deleted')),error:c.req.query('error')??null}));});
assetsRoutes.get('/audios/upload',(c)=>c.html(render('assets/audios/upload.html',{request:{url:c.req.url},user:c.get('user'),error:null})));
assetsRoutes.post('/audios/upload',async(c)=>{const b=await c.req.parseBody(),file=b.file; if(!(file instanceof File)||!['audio/mpeg','audio/mp3','audio/wav','audio/ogg'].includes(file.type)||file.size>25*1024*1024)return c.html(render('assets/audios/upload.html',{request:{url:c.req.url},user:c.get('user'),error:'Invalid file. Allowed: MP3, WAV, OGG up to 25 MB. OGG cannot be used with Twilio.'}),400); const result=await r2Service.uploadAudio(c.env,file.stream(),file.name,file.type); await c.env.DB.prepare("INSERT INTO audios(user_id,name,r2_key,r2_url,content_type,is_active) VALUES(?,?,?,'',?,1)").bind(c.get('user').id,String(b.name??'').trim(),result.key,file.type.toLowerCase()).run(); return c.redirect('/assets/audios?uploaded=true',302);});
assetsRoutes.get('/audios/:id/edit',async(c)=>{const row=await audio(c,idOf(c));if(!row)return c.json({detail:'Audio not found'},404);return c.html(render('assets/audios/edit.html',{request:{url:c.req.url},user:c.get('user'),audio:row,error:null}));});
assetsRoutes.post('/audios/:id/edit',async(c)=>{const id=idOf(c),row=await audio(c,id);if(!row)return c.json({detail:'Audio not found'},404);const b=await c.req.parseBody();await c.env.DB.prepare('UPDATE audios SET name=?,is_active=? WHERE id=?').bind(String(b.name??'').trim(),truthy(b.is_active)?1:0,id).run();return c.redirect('/assets/audios',302);});
assetsRoutes.post('/audios/:id/delete',async(c)=>{const id=idOf(c),row=await audio(c,id);if(!row)return c.json({detail:'Audio not found'},404);const used=await c.env.DB.prepare('SELECT COUNT(*) count FROM campaigns WHERE audio_id=?').bind(id).first<{count:number}>();if(used?.count)return c.redirect('/assets/audios?error='+encodeURIComponent('Cannot delete: this audio is used by campaigns'),302);await c.env.DB.prepare('DELETE FROM audios WHERE id=?').bind(id).run();await r2Service.deleteAudio(c.env,row.r2_key);return c.redirect('/assets/audios?deleted=true',302);});
assetsRoutes.get('/audios/:id/content',async(c)=>{const row=await audio(c,idOf(c));if(!row)return c.json({detail:'Audio not found'},404);const object=await c.env.AUDIO_R2.get(row.r2_key);if(!object)return c.json({detail:'Audio object not found'},404);return new Response(object.body,{headers:{'content-type':object.httpMetadata?.contentType??'application/octet-stream','cache-control':'private, max-age=300'}});});
