// Precompiles Jinja-style templates to JS functions (Workers forbid runtime eval).
// Runs automatically via wrangler "build.command". Output: src/templates_compiled.ts
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import nunjucks from 'nunjucks';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const templatesDir = path.join(root, 'app', 'templates');
const outFile = path.join(root, 'src', 'templates_compiled.ts');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)],
  );
}

const files = walk(templatesDir).filter((f) => f.endsWith('.html')).sort();
const snippets = files.map((f) => {
  const name = path.relative(templatesDir, f);
  const src = fs.readFileSync(f, 'utf8');
  return nunjucks.precompileString(src, { name }).replace(
    /\(window\.nunjucksPrecompiled = window\.nunjucksPrecompiled \|\| \{\}\)/g,
    '(templatesMap)',
  );
});

const out = `// AUTO-GENERATED by scripts/precompile_templates.mjs — do not edit.
// @ts-nocheck
const templatesMap: Record<string, unknown> = {};
${snippets.join('\n')}
export const templates: Record<string, unknown> = templatesMap;
`;

// Only write on change: writing identical content would retrigger wrangler's watcher forever.
const prev = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : null;
if (prev !== out) {
  fs.writeFileSync(outFile, out);
}
console.log(`precompiled ${files.length} templates -> src/templates_compiled.ts`);
