import { createMiddleware } from 'hono/factory';
import { getCookie, setCookie } from 'hono/cookie';
import { verifyToken } from './auth';

// Generated by `wrangler types`; rerun it whenever wrangler.jsonc changes.
export type Env = Cloudflare.Env;

export interface UserRow {
  id: number;
  email: string;
  password_hash: string;
  is_admin: number;
  is_active: number;
  transfer_number: string | null;
  created_at: string;
  updated_at: string;
}

export type AppEnv = { Bindings: Env; Variables: { user: UserRow } };

const SAFE_METHODS = new Set(['GET', 'HEAD', 'OPTIONS']);

class CsrfFormInjector {
  constructor(private readonly token: string) {}

  element(element: Element): void {
    element.append(`<input type="hidden" name="csrf_token" value="${this.token}">`, {
      html: true,
    });
  }
}

export const csrfProtection = createMiddleware<AppEnv>(async (c, next) => {
  const pathname = new URL(c.req.url).pathname;
  const protectedRoute = !pathname.startsWith('/api/') && !['/auth/login', '/auth/register'].includes(pathname);
  const rawToken = getCookie(c, 'csrf_token');
  // Never trust the cookie shape: it is interpolated into HTML and compared for CSRF.
  const token = rawToken && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(rawToken)
    ? rawToken
    : crypto.randomUUID();

  if (protectedRoute && !SAFE_METHODS.has(c.req.method)) {
    const contentType = c.req.header('content-type') ?? '';
    const suppliedHeader = c.req.header('x-csrf-token');
    let suppliedForm: string | undefined;
    if (contentType.includes('application/x-www-form-urlencoded') || contentType.includes('multipart/form-data')) {
      const form = await c.req.raw.clone().formData();
      const value = form.get('csrf_token');
      suppliedForm = typeof value === 'string' ? value : undefined;
    }
    if (!token || (suppliedHeader !== token && suppliedForm !== token)) {
      return c.json({ detail: 'Invalid CSRF token' }, 403);
    }
  }

  await next();
  setCookie(c, 'csrf_token', token, {
    httpOnly: false,
    sameSite: 'Lax',
    secure: new URL(c.req.url).protocol === 'https:',
    path: '/',
    maxAge: 24 * 3600,
  });
  if ((c.res.headers.get('content-type') ?? '').includes('text/html')) {
    c.res = new HTMLRewriter().on('form[method="post" i]', new CsrfFormInjector(token)).transform(c.res);
  }
});

export async function getUser(c: {
  req: { raw: Request };
  env: Env;
}): Promise<UserRow | null> {
  const token = getCookie(c as never, 'access_token');
  if (!token) return null;
  const payload = await verifyToken(c.env.JWT_SECRET, token);
  if (!payload) return null;
  const row = await c.env.DB.prepare('SELECT * FROM users WHERE id = ?')
    .bind(Number(payload.sub))
    .first<UserRow>();
  if (!row || !row.is_active) return null;
  return row;
}

function wantsHtml(c: { req: { raw: Request } }): boolean {
  const accept = c.req.raw.headers.get('accept') ?? '';
  return accept.includes('text/html');
}

export const loadUser = createMiddleware<AppEnv>(async (c, next) => {
  const user = await getUser(c);
  if (user) c.set('user', user);
  await next();
});

export const requireUser = createMiddleware<AppEnv>(async (c, next) => {
  const user = await getUser(c);
  if (!user) {
    if (wantsHtml(c)) return c.redirect('/auth/login', 302);
    return c.json({ detail: 'Not authenticated' }, 401);
  }
  c.set('user', user);
  await next();
});

export const requireAdmin = createMiddleware<AppEnv>(async (c, next) => {
  const user = await getUser(c);
  if (!user) {
    if (wantsHtml(c)) return c.redirect('/auth/login', 302);
    return c.json({ detail: 'Not authenticated' }, 401);
  }
  if (!user.is_admin) return c.json({ detail: 'Admin access required' }, 403);
  c.set('user', user);
  await next();
});

// Python: require_active_rental — non-admins need an active rental, 402 -> /billing for browsers.
export const requireRental = createMiddleware<AppEnv>(async (c, next) => {
  const user = await getUser(c);
  if (!user) {
    if (wantsHtml(c)) return c.redirect('/auth/login', 302);
    return c.json({ detail: 'Not authenticated' }, 401);
  }
  if (!user.is_admin) {
    const now = new Date().toISOString();
    const active = await c.env.DB.prepare(
      "SELECT 1 FROM user_rentals WHERE user_id = ? AND status = 'active' AND expires_at > ? LIMIT 1",
    )
      .bind(user.id, now)
      .first();
    if (!active) {
      if (wantsHtml(c)) return c.redirect('/billing', 302);
      return c.json({ detail: 'Active rental required. Please renew your daily/weekly plan.' }, 402);
    }
  }
  c.set('user', user);
  await next();
});
